"""Initial migration

Revision ID: 088eb92c19a1
Revises: d36108617c07
Create Date: 2025-01-31 00:44:25.190602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '088eb92c19a1'
down_revision = 'd36108617c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.alter_column('unit',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
