"""Initial migratioxxxn

Revision ID: 4f1d0415afd1
Revises: 
Create Date: 2025-05-17 11:54:57.945775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1d0415afd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing_details', schema=None) as batch_op:
        batch_op.drop_constraint('borrowing_details_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'borrowings', ['borrowing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    with op.batch_alter_table('borrowing_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('borrowing_details_ibfk_1', 'borrowings', ['borrowing_id'], ['id'])

    # ### end Alembic commands ###
