"""Initial migration

Revision ID: 7c08c2e378d2
Revises: 
Create Date: 2025-02-13 15:47:34.787589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c08c2e378d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_number', sa.String(length=15), nullable=False))
        batch_op.create_unique_constraint(None, ['reference_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reference_number')

    # ### end Alembic commands ###
