"""Initial migration

Revision ID: a8788467c1ef
Revises: d37f4a10c60b
Create Date: 2025-02-13 16:43:56.577673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8788467c1ef'
down_revision = 'd37f4a10c60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('pending', 'approved', 'cancel', name='borrow_status'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'approved', 'cancel', name='borrow_status'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
