"""Update inventory model

Revision ID: f061fae1fe0c
Revises: 4378079bd668
Create Date: 2025-01-28 18:10:12.849275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f061fae1fe0c'
down_revision = '4378079bd668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('property_no', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_acquired', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fund_source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('officer', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('available', 'borrowed', 'reserved', 'damaged', name='inventory_status'),
               existing_nullable=False)
        batch_op.drop_index('name')
        batch_op.create_unique_constraint(None, ['title'])
        batch_op.create_unique_constraint(None, ['property_no'])
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('quantity')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('available', 'borrowed', 'reserved', 'damaged', name='inventory_status'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('officer')
        batch_op.drop_column('fund_source')
        batch_op.drop_column('unit')
        batch_op.drop_column('cost')
        batch_op.drop_column('date_acquired')
        batch_op.drop_column('property_no')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
